pipeline {
    agent any
    stages {
        stage ("Stage 1 test") {
            steps{
                echo "Stage 1 - command 1"
                echo "Stage 1 - command 2"
                echo "Stage 1 - command 3"
            }
        }
        stage ("Stage 2 test") {
            steps{
                echo "Stage 2 - command 1"
                echo "Stage 2 - command 2"
            }
        }
    }
}